version: '3'

services:
  database:
    image: mysql:5.6.42
    volumes:
      - ./database/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
    networks:
      internal_network:
        ipv4_address: 192.168.0.2

  redis:
    image: redis
    networks:
      internal_network:
        ipv4_address: 192.168.0.3

  proxy:
    build: ./proxy
    privileged: true
    networks:
      internal_network:
        ipv4_address: 192.168.0.10

  server1:
    build: ./server
    privileged: true
    working_dir: /var/www/html/public
    volumes:
      - ./server/src:/var/www/html
    networks:
      internal_network:
        ipv4_address: 192.168.0.11

  server2:
    build: ./server
    privileged: true
    working_dir: /var/www/html/public
    volumes:
      - ./server/src:/var/www/html
    networks:
      internal_network:
        ipv4_address: 192.168.0.12

networks:
  internal_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/24
